version: "3.9"
services:
  processor:
    image: processor
    build: ./data_generation
    volumes:
      - ./data_generation:/code
  app:
    image: sc-drink-app
    build: ./app
    volumes:
      - ./app/src:/code
    ports:
      - 8000:8000
